version: '3.8'

services:
  expo-app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    ports:
      - 19000:19000
      - 19001:19001
      - 19002:19002
    env_file: .env
    volumes:
      - ../source:/home/node/app/source
