version: '3.8'

services:
  expo-app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    env_file: .env
    ports:
      - '19000:19000'
      - '19001:19001'
      - '19002:19002'
    volumes:
      - ..:/app
