version: '3.8'

services:
  expo-app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    ports:
      - 19000:19000
      - 19001:19001
      - 19002:19002
      - 19003:19003
      - 19004:19004
      - 19005:19005
      - 19006:19006
    env_file: .env
    volumes:
      - ../source:/home/node/app/source
    stdin_open: true
    tty: true
