name: Lint and Format TypeScript

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - '**.tsx?'

jobs:
  eslint:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install dependencies
      uses: borales/actions-yarn@v2.3.0
      with:
        cmd: install
    - name: Run prettier
      uses: borales/actions-yarn@v2.3.0
      with:
        cmd: run format
    - name: Run eslint
      uses: borales/actions-yarn@v2.3.0
      with:
        cmd: run lint