name: Unit Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install dependencies
      uses: borales/actions-yarn@v2.3.0
      with:
        cmd: install
    - name: Run unit tests
      uses: borales/actions-yarn@v2.3.0
      with:
        cmd: test